stages:
  - build

build job:
  stage: build
  image: electronuserland/builder:wine
  #only:
  #  - tags
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*.*
  script:
    - sed  -i '/version/s/[^.]*$/'"${CI_COMMIT_TAG}\"/" package.json
    - yarn -v
    - yarn install && yarn build