stages:
  - build

build:
  stage: build
  image: electronuserland/builder:wine
  only:
    - master
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*.*
  script:
    - sed "s/0.0.0/1.0.0/g" package.json > _package.json && mv _package.json package.json
    # - sed "s/0.0.0/${CI_COMMIT_TAG}/g" package.json
    - yarn && yarn build:all