stages:
  - build

build:
  image: slauta93/electron-builder-win
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*.*
  script:
    - sed  -i '/version/s/[^.]*$/'"${CI_COMMIT_TAG}\"/" package.json
    - yarn -v
    - yarn install && yarn build