version: '3'
services:
  mariadb:
    restart: always
    image: 'bitnami/mariadb:latest'
    ports:
      - 3310:3306
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_DATABASE: askc
      MARIADB_USER: askc
      MARIADB_PASSWORD: askc
    volumes:
      - mysqldata:/bitnami
  web:
    restart: always
    image: php:7.2-apache
    ports:
      - 8083:80
    volumes:
      - ./dist:/var/www/html
volumes:
  mysqldata:
    driver: local